### ISSUE TITLE
(P3) X-Axis tick values are overlapping when screen resized - see screenshot

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-vis-boxplot#45]
![screen shot 2018-02-05 at 5 22 38 pm](https://user-images.githubusercontent.com/21231643/35837217-6c270868-0a99-11e8-8704-3e740f508b99.png)

**Comment by nonmetalhail** [comment]
There is nothing you can do about this. End developers will have to reduce the number of ticks when they work with a small screen. You can close this issue
