### ISSUE TITLE
(P2) X-Axis truncated, if move to the Top in configuration in demo

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-vis-boxplot#46]
![screen shot 2018-02-05 at 5 43 19 pm](https://user-images.githubusercontent.com/21231643/35837652-32f211c0-0a9c-11e8-9c1d-162a2ec33fbc.png)

**Comment by drewharvey** [comment]
If the application changes the xAxisConfig to position the xAxis on the top, shouldn't the application update the margins to give the top more space?

**Comment by nonmetalhail** [comment]
Sorry, just looking at these issues now, but yes, this is an application setting. You should not reverse the margins as you have done. Please revert this change. This is not an issue
