### ISSUE TITLE
(P2) In Demo, changing configuration for Y-axis or X-axis label from center to right or left has no effect

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-vis-boxplot#47]
In Demo, changing configuration for X-axis label from center to right or left has no effect

**Comment by Aileen-H** [comment]
Still doesn't seem to have any effect on label position. Should be re-opened. Tag 0.3

**Comment by alump** [comment]
@drewharvey what went wrong?

**Comment by drewharvey** [comment]
The correct values for labelPosition are 'center', 'before', and 'after'.  This is working as expected.  Note that there is a bug in the px-vis-axis component with the 'before' position.  However, that is a separate issue and not related to this.

Property: labelPosition

https://www.predix-ui.com/#/elements/vis/px-vis/px-vis-axis

**Comment by drewharvey** [comment]
Closing as no issue here.  The incorrect values were used in test.
