### ISSUE TITLE
X- and Y-axis number position (with screenshots)

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-vis-boxplot#49]
**Current state of the numbers is centered:**
<img width="485" alt="screen shot 2018-02-08 at 10 44 09 am" src="https://user-images.githubusercontent.com/30873778/35991820-4520ff14-0cbd-11e8-8955-933ee081ff44.png">
<img width="64" alt="screen shot 2018-02-08 at 10 44 04 am" src="https://user-images.githubusercontent.com/30873778/35991821-4855fcc0-0cbd-11e8-9535-6f96bbf8c3c6.png">

**Expected state is positioned to the right on the X-axis and top aligned on the Y-axis:**
<img width="994" alt="screen shot 2018-02-08 at 10 43 48 am" src="https://user-images.githubusercontent.com/30873778/35991902-8650305e-0cbd-11e8-9408-3d1522ea5a76.png">
<img width="66" alt="screen shot 2018-02-08 at 10 43 54 am" src="https://user-images.githubusercontent.com/30873778/35991906-894eaa92-0cbd-11e8-8dac-03074e6d609b.png">

**Comment by nonmetalhail** [comment]
The positions follow vis standard. This can be closed.
