### ISSUE TITLE
Change opacity code

### ISSUE THREAD

**Issue by nonmetalhail** [vaadin/px-vis-boxplot#61]
This section should be changed:[https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L627-L656]( https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L627-L656)

Instead, apply the opacity with a css class from the px-vis styles, `.primaryDataMask`. You should also apply the `.hoverTransition` to the elements which will be getting the opacity change to get the transition.

Also, there should not be a delay. Remove the delay from the opacity and the tooltip

**Comment by alump** [comment]
@drewharvey why delay was added?

**Comment by nonmetalhail** [comment]
I believe tooltip ships with a default delay, so he was probably just matching that delay. But instead, it should be removed

**Comment by drewharvey** [comment]
Yes I was just matching the default delay on the tooltip.

**Comment by Aileen-H** [comment]
Priority 2
