### ISSUE TITLE
Empty array for chartData should be valid

### ISSUE THREAD

**Issue by nonmetalhail** [vaadin/px-vis-boxplot#62]
This line prevents an empty array for chartData from working: [https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L388](https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L388)

An empty array should clear drawn boxes off of the chart and should be handled

**Comment by Aileen-H** [comment]
Priority 2
