### ISSUE TITLE
remove direct calls to drawElement()

### ISSUE THREAD

**Issue by nonmetalhail** [vaadin/px-vis-boxplot#63]
Lines:
[https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L535](https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L535)
[https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L543](https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-boxplot.html#L543)

The axes *should* redraw when their properties change so this call should not be needed. If this doesnt work, then we should fix it in axis.

**Comment by Aileen-H** [comment]
Priority 2
