### ISSUE TITLE
Remove hard coded title from X and Y axis

### ISSUE THREAD

**Issue by benoitjchevalier** [vaadin/px-vis-boxplot#66]
title="Y Axis"

**Comment by alump** [comment]
@drewharvey - i was trying to do this, but I'm little lost how we do axis mapping. And how we map axis configs to axises. If i just remove the title, then "title" value from axis config is not applied.

**Comment by alump** [comment]
Also check that labels of axises work with poly 1.x, I noticed that those are missing totally.

**Comment by Aileen-H** [comment]
Priority P2
