### ISSUE TITLE
P3 DEMO: Toggle for dark theme/light theme in Demo is incorrectly labeled (reversed)

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-vis-boxplot#71]
Expected Behavior: Click on dark theme toggle to see demo in dark theme.

Actual Behavior: Click on light theme toggle to see demo in dark theme.

**Comment by nonmetalhail** [comment]
This is not an issue and should be closed as it will rely on predix-ui switcher when it is delivered
